<?php
/** @var $person Application_Model_Person */
$person = $this->person;
?>

<br /><br />
<div id="view-content">
	<div>
        <h3>Name</h3>
        <p><?php echo $person->getName() ?></p>
    </div>
    <div>
        <h3>E-mail</h3>
        <p><?php echo $person->getEmail() ?></p>
    </div>
    <div>
        <h3>Telefone</h3>
        <p><?php echo $person->getPhone() ?></p>
    </div>
    <div>
        <h3>CPF</h3>
        <p><?php echo $person->getCpf() ?></p>
    </div>
    <a href="<?php echo '/person/delete/' . $person->getId() ?>">Delete</a>
</div>